version: '3.6'

services:
  # Application
  uwsgi:
    image: amityhorror/flask_base:latest
    env_file: envs/app.env
    configs:
    - source: start_flask
      target: /var/start_flask.sh
      mode: 0755
    - source: uwsgi_ini
      target: /uwsgi/uwsgi.ini
    networks:
    - proxy_network
    ports:
    - "5000:8001"
    command: sh /var/start_flask.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  # Worker Process + Scheduler
  worker:
    image: amityhorror/flask_base:latest
    env_file: envs/app.env
    working_dir: /var
    configs:
    - source: start_celery
      target: /var/start_celery.sh
      mode: 0755
    networks:
    - proxy_network
    command: sh /var/start_celery.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  proxy_network:
    external: true

configs:
  start_flask:
    file: ./start_flask.sh
  start_celery:
    file: ./start_celery.sh
  uwsgi_ini:
    file: ./uwsgi.ini
