version: '3.6'

services:
  # Application
  uwsgi:
    image: amityhorror/flask_base:dev
    env_file: envs/prod.env
    configs:
      - source: start_uwsgi
        target: /var/start_uwsgi.sh
        mode: 0755
      - source: uwsgi_ini
        target: /uwsgi/uwsgi.ini
    networks:
      - proxy_network
    ports:
      - "5000:8001"
    command: sh /var/start_uwsgi.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  # Worker Process + Scheduler
  worker:
    image: amityhorror/flask_base:dev
    env_file: envs/prod.env
    configs:
      - source: start_worker
        target: /var/start_worker.sh
        mode: 0755
    networks:
      - proxy_network
    command: sh /var/start_worker.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  proxy_network:
    external: true

configs:
  start_uwsgi:
    file: ./configs/start_uwsgi.sh
  start_worker:
    file: ./configs/start_worker.sh
  uwsgi_ini:
    file: ./configs/uwsgi.ini
