version: '3.6'

services:
  # Broker GUI management
  flower:
    image: amityhorror/flask_base:latest
    env_file: envs/app.env
    networks:
    - proxy_network
    ports:
    - "5001:5555"
    working_dir: /var
    command: celery flower -A modules.worker.celery
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  # Message Broker
  rabbit:
    image: rabbitmq:3.6.6-management
    env_file: envs/app.env
    ports:
    - "5672"
    - target: 25672
      published: 25672
      protocol: tcp
      mode: host
    networks:
    - proxy_network
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  proxy_network:
    external: true
