version: '3.6'

services:
  # Broker GUI management
  flower:
    image: amityhorror/flask_base
    env_file: envs/app.env
    networks:
    - proxy_network
    ports:
    - target: 5555
      published: 5001
      protocol: tcp
      mode: ingress
    working_dir: /var
    command: celery flower -A modules.celery_worker.celery
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  # Message Broker
  rabbit:
    image: rabbitmq:3.6.6-management
    env_file: envs/app.env
    ports:
    - target: 5672
      published: 5672
      protocol: tcp
      mode: ingress
    - target: 25672
      published: 25672
      protocol: tcp
      mode: ingress
    networks:
    - proxy_network
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  proxy_network:
    external: true
