version: '3.6'

services:
  # Docker GUI management
  gui:
    image: portainer/portainer
    ports:
    - target: 9000
      published: 33333
      protocol: tcp
      mode: host
    volumes:
    - portainer_data:/data
    depends_on:
    - agent
    networks:
    - portainer_agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # Management's connection to Docker
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    ports:
    - target: 9001
      published: 9001
      protocol: tcp
      mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
    - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

volumes:
  portainer_data:

networks:
  portainer_agent:
    driver: overlay
    attachable: true
