version: '3.6'

services:
  # Task Broker for network
  rabbit:
    image: rabbitmq:3.6.6-management
    env_file: envs/app.env
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager] #[node.platform.os == linux]

  # Docker GUI management
  portainer:
    image: portainer/portainer
    ports:
      - "33333:9000"
    volumes:
      - portainer_data:/data
    depends_on:
      - agent
    networks:
      - portainer_agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # Connect GUI management to docker
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

volumes:
  portainer_data:

networks:
  portainer_agent:
    driver: overlay
    attachable: true
