version: '2'

services:
  website:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    env_file:
      - ./flask.env
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../tmp:/var/www/tmp
#    command: uwsgi --ini uwsgi.ini
    command: ./run
    restart: always

#  nginx:
#    build:
#      context: .
#      dockerfile: ./nginx/Dockerfile
#    links:
#      - website
#      - flower
#    volumes_from:
#      - website:ro
#    ports:
#      - "80:80"
#      - "443:443"
#    command: nginx -c nginx.conf
#    restart: always

  rabbit:
    image: rabbitmq:latest
    env_file:
      - ./flask.env

#  flower:
#    build:
#      context: .
#      dockerfile: ./celery/Dockerfile
#    environment:
#      DISCOVER_RABBITMQ: "true"
#    depends_on:
#      - rabbit
#    links:
#      - website
#      - rabbit
#    volumes_from:
#      - website:ro
#    ports:
#      - "5555:5555"
#    command: flower --config flower_config.py
#    restart: always

  celeryworker:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    env_file:
      - ./flask.env
    volumes_from:
      - website
    depends_on:
      - rabbit
    links:
      - website
      - rabbit
    command: ./run_worker

  celerybeat:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    env_file:
      - ./flask.env
    volumes_from:
      - website
    depends_on:
      - rabbit
    links:
      - website
      - rabbit
    command: ./run_beat
