version: '2'

services:
  # Task Broker
  rabbit:
    image: rabbitmq:latest
    env_file: app.env

  # Flask Images/Controller/View/Worker Layers
  uwsgi:
    build:
      context: uwsgi
      dockerfile: Dockerfile
    env_file: app.env
    volumes:
      - ./uwsgi/uwsgi.ini:/uwsgi/uwsgi.ini
      - ./uwsgi/wsgi.py:/app/wsgi.py
      - ../backend:/app/backend
      - ../instance:/app/instance
      - ../static:/app/static
      - asset-volume:/tmp
    depends_on:
      - postgres
    working_dir: /uwsgi
    command: uwsgi --thunder-lock --ini /uwsgi/uwsgi.ini
    restart: always

  worker:
    build:
      context: uwsgi
      dockerfile: Dockerfile
    env_file: app.env
    volumes_from:
      - uwsgi
    depends_on:
      - rabbit
    working_dir: /app
    command: celery -A backend.celery worker -l info

  beat:
    build:
      context: uwsgi
      dockerfile: Dockerfile
    env_file: app.env
    volumes_from:
      - uwsgi
    depends_on:
      - rabbit
    working_dir: /app
    command: celery -A backend.celery beat -l info

  flower:
    build:
      context: uwsgi
      dockerfile: Dockerfile
    env_file: app.env
    volumes_from:
      - uwsgi
    depends_on:
      - rabbit
    ports:
      - "5555"
    working_dir: /app
    command: celery -A backend.celery flower

  # Data Layers
  data:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    volumes_from:
      - data
    ports:
      - "5432"

  # Reverse proxy LB
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - asset-volume:/tmp
    links:
      - uwsgi
      - flower
    ports:
      - "80:80"
      - "5555:5555"
    command: nginx -c nginx.conf
    restart: always

# Shared volume exposes sockets/pid files
volumes:
  asset-volume: